name: 'Reusable Workflow'

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: true
        type: string
      run-tests:
        description: 'Whether to run tests'
        required: false
        default: 'true'
        type: boolean

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs['node-version'] }}

    - name: Install dependencies
      run: npm install

    - name: Run tests
      if: ${{ inputs['run-tests'] == 'true' }}
      run: npm test