name: Continuous Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  deploy-dev:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      environment: dev
      branch: main
    secrets: inherit

  deploy-test:
    uses: ./.github/workflows/reusable-workflow.yml
    # needs: deploy-dev
    with:
      environment: tst
      branch: main
    secrets: inherit