# name: Continuous Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string
      branch:
        description: 'The branch to run the apply job on'
        required: true
        type: string        

permissions:
  id-token: write
  contents: read
  pull-requests: write

defaults:
  run:
    shell: pwsh


jobs:
  deploy-dev:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      environment: dev
      branch: main
    secrets: inherit

  deploy-test:
    uses: ./.github/workflows/reusable-workflow.yml
    needs: deploy-dev
    with:
      environment: tst
      branch: main
    secrets: inherit
  
  deploy-pre:
    uses: ./.github/workflows/reusable-workflow.yml
    needs: deploy-test
    with:
      environment: pre
      branch: main
    secrets: inherit