name: Terraform Plan and Apply

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string
      branch:
        description: 'The branch to run the apply job on'
        required: true
        type: string

#Special permissions required for OIDC authentication
# permissions:
#   id-token: write
#   contents: read
#   pull-requests: write

env:
  # ARM_CLIENT_ID: ${{ secrets['AZURE_CLIENT_ID_${{ inputs.environment | upper }}'] }}
  # ARM_SUBSCRIPTION_ID: ${{ secrets['AZURE_SUBSCRIPTION_ID_${{ inputs.environment | upper }}'] }}
  # ARM_TENANT_ID: ${{ secrets['AZURE_TENANT_ID_${{ inputs.environment | upper }}'] }}
  # ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  # ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  # ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # - name: Azure Login
    #   uses: azure/login@v1
    #   with:
    #     client-id: ${{ secrets['AZURE_CLIENT_ID_${{ inputs.environment | upper }}'] }}
    #     tenant-id: ${{ secrets['AZURE_TENANT_ID_${{ inputs.environment | upper }}'] }}
    #     subscription-id: ${{ secrets['AZURE_SUBSCRIPTION_ID_${{ inputs.environment | upper }}'] }}

    - name: Terraform Init
      run: terraform init -backend-config=backend-${{ inputs.environment }}.conf
      env:
        ARM_CLIENT_ID: ${{ secrets['AZURE_CLIENT_ID_${{ inputs.environment | upper }}'] }}
        ARM_SUBSCRIPTION_ID: ${{ secrets['AZURE_SUBSCRIPTION_ID_${{ inputs.environment | upper }}'] }}
        ARM_TENANT_ID: ${{ secrets['AZURE_TENANT_ID_${{ inputs.environment | upper }}'] }}

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Save Plan
      uses: actions/upload-artifact@v4
      with:
        name: tfplan-${{ inputs.environment }}
        path: tfplan

  terraform-apply:
    name: 'Terraform Apply'
    if: github.ref == 'refs/heads/${{ inputs.branch }}'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: terraform-plan

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # - name: Azure Login
    #   uses: azure/login@v1
    #   with:
    #     client-id: ${{ secrets['AZURE_CLIENT_ID_${{ inputs.environment | upper }}'] }}
    #     tenant-id: ${{ secrets['AZURE_TENANT_ID_${{ inputs.environment | upper }}'] }}
    #     subscription-id: ${{ secrets['AZURE_SUBSCRIPTION_ID_${{ inputs.environment | upper }}'] }}

    - name: Terraform Init
      run: terraform init -backend-config=backend-${{ inputs.environment }}.conf

    - name: Download Terraform Plan
      uses: actions/download-artifact@v4
      with:
        name: tfplan-${{ inputs.environment }}

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan

    # env:
    #   ARM_CLIENT_ID: ${{ secrets['AZURE_CLIENT_ID_${{ inputs.environment | upper }}'] }}
    #   ARM_SUBSCRIPTION_ID: ${{ secrets['AZURE_SUBSCRIPTION_ID_${{ inputs.environment | upper }}'] }}
    #   ARM_TENANT_ID: ${{ secrets['AZURE_TENANT_ID_${{ inputs.environment | upper }}'] }}