name: Continuous Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  deploy:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      environment: dev
      branch: main
    secrets:
      client_id: ${{ secrets.ARM_CLIENT_ID }}
      subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      tenant_id: ${{ secrets.ARM_TENANT_ID }}